create table spring_ai_chat_history
(
    id bigint generated by default as identity primary key,
    content    text,
    created_at timestamp(6),
    type       varchar(255)
        constraint spring_ai_chat_history_type_check
            check ((type)::text = ANY ((ARRAY ['USER'::character varying, 'ASSISTANT'::character varying, 'SYSTEM'::character varying, 'TOOL'::character varying])::text[])),
    user_id    varchar(255)
);