# application-local.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/n8n
    username: n8n
    password: "@tndmsgh2122"
    driver-class-name: org.postgresql.Driver

  # Spring AI
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key-here}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-3-small

    # Vector Store
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        table-name: vector_store
        schema-name: public